#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Set border width and colors
bspc config window_gap 16
bspc config border_width 0
bspc config normal_border_color \#DEEEEA
bspc config focused_border_color \#00C1D4

# Application rules
bspc rule -a "Tor Browser" state=floating
